CREATE USER "31882_2025_Credo_VehicleRental_DB" IDENTIFIED BY "ChangeMe123!";
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE,
      CREATE TRIGGER, CREATE TYPE, UNLIMITED TABLESPACE TO "31882_2025_Credo_VehicleRental_DB";


