

SET DEFINE OFF;

CREATE TABLE branches (
  branch_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_name  VARCHAR2(100) NOT NULL,
  address      VARCHAR2(200),
  phone        VARCHAR2(20)
);


CREATE TABLE vehicles (
  vehicle_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reg_number     VARCHAR2(20) NOT NULL UNIQUE,
  make_model     VARCHAR2(100),
  year_manufact  NUMBER(4) CHECK (year_manufact BETWEEN 1900 AND EXTRACT(YEAR FROM SYSDATE)+1),
  category       VARCHAR2(50),
  daily_rate     NUMBER(10,2) CHECK (daily_rate >= 0),
  status         VARCHAR2(20) DEFAULT 'AVAILABLE' -- AVAILABLE, RENTED, MAINTENANCE
);


CREATE TABLE customers (
  customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name     VARCHAR2(150) NOT NULL,
  phone         VARCHAR2(20),
  email         VARCHAR2(100) UNIQUE,
  license_no    VARCHAR2(50),
  joined_date   DATE DEFAULT TRUNC(SYSDATE)
);

CREATE TABLE rentals (
  rental_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id     NUMBER NOT NULL,
  customer_id    NUMBER NOT NULL,
  branch_id      NUMBER NOT NULL,
  start_date     DATE NOT NULL,
  end_date       DATE,
  daily_rate     NUMBER(10,2) NOT NULL,
  total_amount   NUMBER(12,2) DEFAULT 0 CHECK (total_amount >= 0),
  status         VARCHAR2(20) DEFAULT 'ACTIVE', -- ACTIVE, CLOSED, CANCELLED
  CONSTRAINT fk_rental_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id),
  CONSTRAINT fk_rental_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_rental_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id)
);


CREATE TABLE payments (
  payment_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rental_id     NUMBER NOT NULL,
  pay_date      DATE DEFAULT SYSDATE,
  amount        NUMBER(12,2) CHECK (amount >= 0),
  method        VARCHAR2(50),
  CONSTRAINT fk_payment_rental FOREIGN KEY (rental_id) REFERENCES rentals(rental_id) ON DELETE CASCADE
);


CREATE TABLE maintenance (
  maintenance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id     NUMBER NOT NULL,
  maint_date     DATE DEFAULT SYSDATE,
  description    VARCHAR2(4000),
  cost           NUMBER(12,2) DEFAULT 0,
  CONSTRAINT fk_maint_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id)
);


CREATE TABLE public_holidays (
  holiday_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_date  DATE NOT NULL UNIQUE,
  description   VARCHAR2(200)
);


CREATE TABLE audit_log (
  audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_ts      TIMESTAMP DEFAULT SYSTIMESTAMP,
  username      VARCHAR2(100),
  operation     VARCHAR2(10), -- INSERT, UPDATE, DELETE
  table_name    VARCHAR2(100),
  pk_value      VARCHAR2(200),
  old_values    CLOB,
  new_values    CLOB
);

COMMIT;

INSERT INTO branches (branch_name, address, phone) VALUES ('Kigali Central', 'KK 508 ST', '+250791000111');
INSERT INTO branches (branch_name, address, phone) VALUES ('Gasabo North', 'KK 301', '+250791000222');

INSERT INTO vehicles (reg_number, make_model, year_manufact, category, daily_rate, status)
VALUES ('RAB123A', 'Toyota Wyn', 2018, 'Economy', 30.00, 'AVAILABLE');
INSERT INTO vehicles (reg_number, make_model, year_manufact, category, daily_rate, status)
VALUES ('RAB456B', 'Toyota Prado', 2020, 'SUV', 60.00, 'AVAILABLE');

INSERT INTO customers (full_name, phone, email, license_no)
VALUES ('Alice Example', '+250788000111', 'alice@example.com', 'RWN-123456');
INSERT INTO customers (full_name, phone, email, license_no)
VALUES ('Bob Sample', '+250788000222', 'bob@example.com', 'RWN-654321');


INSERT INTO public_holidays (holiday_date, description) VALUES (TO_DATE('2026-07-01','YYYY-MM-DD'), 'Independence Day');

COMMIT;
